# Decompressed Demo Configuration - Without check_markers

# Launch Configuration
launch_config:
  ros__parameters:
    enable_check_markers: false  # Disable check_markers node
    enable_rviz: true            # Keep RViz enabled

# Pointcloud Compressor Node Parameters
pointcloud_compressor_node:
  ros__parameters:
    # Input/Output settings
    input_pcd_file: "/home/ryo/tsudanuma/maps/tsudanuma-challenge-all.ply"
    voxel_size: 1.0
    min_points_threshold: 50

    # Compression Settings
    use_voxel_filter: true
    publish_once: true  # Publish only once for demo
    publish_patterns: true
    publish_occupied_voxel_markers: true
    publish_pattern_dictionary: true
    enable_visualization: true

    # ROS Settings
    use_sim_time: false

# Decompressed Viewer Node Parameters
decompressed_viewer_node:
  ros__parameters:
    # Topic Configuration
    pattern_dictionary_topic: "pattern_dictionary"
    pattern_markers_topic: "pattern_markers"

    # Visualization Settings
    frame_id: "map"
    show_pattern_visualization: true

    # ROS Settings
    use_sim_time: false

# Check Markers Node Parameters (not used when disabled)
marker_checker_node:
  ros__parameters:
    # Topics to compare
    marker_array_topic1: "/occupied_voxel_markers"
    marker_array_topic2: "/pattern_markers"

    # Comparison tolerances
    position_tolerance: 1.0e-6
    scale_tolerance: 1.0e-6